/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    DatabaseTableColumns: typeof import('./components/DatabaseTable/DatabaseTableColumns.vue')['default']
    DatabaseTableIndexes: typeof import('./components/DatabaseTable/DatabaseTableIndexes.vue')['default']
    DatabaseTableList: typeof import('./components/DatabaseTable/DatabaseTableList.vue')['default']
    DatabaseTableRelations: typeof import('./components/DatabaseTable/DatabaseTableRelations.vue')['default']
    DatabaseTableStructure: typeof import('./components/DatabaseTable/DatabaseTableStructure.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    IconKeyVerticalOutline: typeof import('./icons/IconKeyVerticalOutline.vue')['default']
    IconQuestion: typeof import('./icons/IconQuestion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    StateList: typeof import('./components/StateList/StateList.vue')['default']
    StateListFooter: typeof import('./components/StateList/StateListFooter.vue')['default']
    StateListHeader: typeof import('./components/StateList/StateListHeader.vue')['default']
    StateListProvider: typeof import('./components/StateList/StateListProvider.vue')['default']
    ZoomMenu: typeof import('./components/tools/ZoomMenu.vue')['default']
  }
}
