/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    DatabaseTableColumns: typeof import('./editor/database-table-structure/DatabaseTableColumns.vue')['default']
    DatabaseTableIndexes: typeof import('./editor/database-table-structure/DatabaseTableIndexes.vue')['default']
    DatabaseTableList: typeof import('./editor/database-table-list/DatabaseTableList.vue')['default']
    DatabaseTableRelations: typeof import('./editor/database-table-structure/DatabaseTableRelations.vue')['default']
    DatabaseTableStructure: typeof import('./editor/database-table-structure/DatabaseTableStructure.vue')['default']
    Editor: typeof import('./editor/Editor.vue')['default']
    IconKeyVerticalOutline: typeof import('./icons/IconKeyVerticalOutline.vue')['default']
    IconQuestion: typeof import('./icons/IconQuestion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
