/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    InteractiveView: typeof import('./components/example/InteractiveView.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    OrganizationChart: typeof import('./components/example/OrganizationChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCheckbox: typeof import('vuetify/components')['VCheckbox']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDivider: typeof import('vuetify/components')['VDivider']
    VirtualList: typeof import('./components/VirtualList.vue')['default']
    VItems: typeof import('vuetify/components')['VItems']
    VList: typeof import('vuetify/components')['VList']
    VRadio: typeof import('vuetify/components')['VRadio']
    VRangeSlider: typeof import('vuetify/components')['VRangeSlider']
    VRow: typeof import('vuetify/components')['VRow']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
