/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    InteractiveView: typeof import('./components/example/InteractiveView.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    OrganizationChart: typeof import('./components/example/OrganizationChart.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
  }
}
