pipeline:
  identifier: Build_lingjhf_interactiver_1711871096675
  name: Build interactiver
  orgIdentifier: default
  projectIdentifier: test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1711763307770
        repoName: lingjhf/interactiver
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: lint
                  name: lint
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
